/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencias_de_viajes;
//import Agencias_de_viajes.Conectar;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author flavioantonio
 */
public class Cliente extends javax.swing.JFrame {

    DefaultTableModel mode1;
    Connection conn;
    Statement sent;
     Consultas_sql_1 x = new Consultas_sql_1();
    public User user_data;

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        conn = Conectar.geConnection();
       // Llenar_combox();

    }
    
    public Cliente(User user) throws SQLException{
        initComponents();
        conn = Conectar.geConnection();
        user_data = user;
        Llenar_combox();
    }
    

    void Llenar_combox() throws SQLException {
    DefaultComboBoxModel model_combox = new DefaultComboBoxModel();
      
     
        
        String sql = "";
        if (user_data.getTipo_empleado() == 1) {
            sql = "SELECT CONCAT (CVE_TIPO_EMPLEADO,'-',DESCRIPCION) FROM tipo_usuario";
        } else if (user_data.getTipo_empleado() == 2) {
            sql = "SELECT CONCAT (CVE_TIPO_EMPLEADO,'-',DESCRIPCION) FROM tipo_usuario where cve_tipo_usuario = 3 ";
        } else if (user_data.getTipo_empleado() == 3) {
            tipo_empleado.setVisible(false);
          }
       
           sent = conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            while (rs.next()) {
               model_combox.addElement(rs.getString(1));
            }
            tipo_empleado.setModel(model_combox);
        
        
        Llenar();
    }

    void Llenar() {

        try {

            conn = Conectar.geConnection();
            String valor[] = (tipo_empleado.getSelectedItem().toString()).split("-");
            
            String[] titulos = {"CVE_PERSONA", "NOMBRE", "PATERNO", "MATERNO", "TELEFONO", "USUARIO", "PASSWORD"};
            String sql = "SELECT * FROM personas inner join usuario on CVE_PERSONA = CVE_USUARIO WHERE usuario.CVE_TIPO_USUARIO = " + valor[0];
          
            System.out.println(sql);
            mode1 = new DefaultTableModel(null, titulos);
            
            
            
            sent = conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);

            String[] fila = new String[7];
            while (rs.next()) {
                fila[0] = rs.getString("CVE_PERSONA");
                fila[1] = rs.getString("NOMBRE");
                fila[2] = rs.getString("PATERNO");
                fila[3] = rs.getString("MATERNO");
                fila[4] = rs.getString("TELEFONO");
                fila[5] = rs.getString("USUARIO");
                fila[6] = rs.getString("PASSWORD");
                mode1.addRow(fila);
            }
            jTable1.setModel(mode1);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    void Desahabilitar() {

        nom1.setEditable(false);
        apa1.setEditable(false);
        ama1.setEditable(false);
        tel1.setEditable(false);
        mai1.setEditable(false);

    }

    void Limpiar() {

        nom1.setText("");
        apa1.setText("");
        ama1.setText("");
        tel1.setText("");
        mai1.setText("");
        cve_persona.setText("");
        txtPassword.setText("");
        txt_usuario.setText("");

    }

    void Habilitar() {

        nom1.setEditable(true);
        apa1.setEditable(true);
        ama1.setEditable(true);
        tel1.setEditable(true);
        mai1.setEditable(true);
        nom1.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nom = new javax.swing.JLabel();
        apa = new javax.swing.JLabel();
        ama = new javax.swing.JLabel();
        tel = new javax.swing.JLabel();
        mai = new javax.swing.JLabel();
        tipo_empleado = new javax.swing.JComboBox<>();
        nom1 = new javax.swing.JTextField();
        apa1 = new javax.swing.JTextField();
        ama1 = new javax.swing.JTextField();
        tel1 = new javax.swing.JTextField();
        mai1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cve_persona = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        label_message_user = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 24))); // NOI18N

        nom.setText("Nombre");

        apa.setText("Apellido Paterno");

        ama.setText("Apellido Materno");

        tel.setText("Telefono");

        mai.setText("Correo Electronico");

        tipo_empleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Empleado", "Sin Cuenta" }));
        tipo_empleado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipo_empleadoItemStateChanged(evt);
            }
        });
        tipo_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_empleadoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton5.setText("Menu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cve_persona.setEnabled(false);

        jLabel1.setText("IDENTIFICADOR");

        jLabel2.setText("Usuario");

        jLabel3.setText("Password");

        txt_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usuarioKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mai)
                            .addComponent(tel)
                            .addComponent(apa)
                            .addComponent(ama)
                            .addComponent(nom)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cve_persona)
                            .addComponent(tipo_empleado, 0, 250, Short.MAX_VALUE)
                            .addComponent(ama1)
                            .addComponent(tel1)
                            .addComponent(mai1)
                            .addComponent(nom1)
                            .addComponent(apa1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_usuario)
                            .addComponent(txtPassword))
                        .addGap(18, 18, 18)
                        .addComponent(label_message_user, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tipo_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cve_persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom)
                    .addComponent(nom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apa)
                    .addComponent(apa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ama)
                    .addComponent(ama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel)
                    .addComponent(tel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mai)
                    .addComponent(mai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_message_user, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(jButton5))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipo_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_empleadoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        dispose();


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == 1) {

            int row = jTable1.getSelectedRow();
            cve_persona.setText(jTable1.getValueAt(row, 0).toString());
            nom1.setText(jTable1.getValueAt(row, 1).toString());
            apa1.setText(jTable1.getValueAt(row, 2).toString());
            ama1.setText(jTable1.getValueAt(row, 3).toString());
            tel1.setText(jTable1.getValueAt(row, 4).toString());
            txt_usuario.setText(jTable1.getValueAt(row, 5).toString());
            txtPassword.setText(jTable1.getValueAt(row, 6).toString());
//            mai1.setText(jTable1.getValueAt(row, 5).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            int datos = jTable1.getSelectedRow();
            String sql = "delete from `personas` where `CVE_PERSONA` = " + jTable1.getValueAt(datos, 0);
            sent = conn.createStatement();
            int n = sent.executeUpdate(sql);
            if (n > 0) {
                Llenar();

            }
            JOptionPane.showMessageDialog(null, "Datos eliminados");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String sql = "UPDATE `agencias_de_viajes`.`personas` SET  NOMBRE = ?, PATERNO = ?, MATERNO = ?, TELEFONO = ?, E-mail = ?   WHERE  Id_Viajes = ?";
            int datos = jTable1.getSelectedRow();
            String dao = (String) jTable1.getValueAt(datos, 0);
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, nom1.getText());
            ps.setString(2, apa1.getText());
            ps.setString(3, ama1.getText());
            ps.setString(4, tel1.getText());
            ps.setString(5, mai1.getText());

//ps.setString(1, paq1.getText());
            ps.setString(1, dao);
            // System.out.println(sql);
            int n = ps.executeUpdate();
            if (n > 0) {
                Limpiar();
                Llenar();
                JOptionPane.showMessageDialog(null, "Datos Modificados");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex.getMessage());
            // Logger.getLogger(Viajes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tipo_empleadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipo_empleadoItemStateChanged
      if (user_data != null){
          Llenar();
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_empleadoItemStateChanged

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
     Limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txt_usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usuarioKeyPressed
      

        String name_table = "usuario";
        String busqueda[][] = new String[1][2];
        busqueda[0][0] = "usuario";
        busqueda[0][1] = txt_usuario.getText();
     
        ResultSet rs;
        try {
            rs = x.search(name_table, busqueda);
             if (rs != null) {
            while (rs.next()) {
                 label_message_user.setText("USUARIO NO DISPONIBLE");
            }
        }else {
                label_message_user.setText("");
             }
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_txt_usuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ama;
    private javax.swing.JTextField ama1;
    private javax.swing.JLabel apa;
    private javax.swing.JTextField apa1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JTextField cve_persona;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_message_user;
    private javax.swing.JLabel mai;
    private javax.swing.JTextField mai1;
    private javax.swing.JLabel nom;
    private javax.swing.JTextField nom1;
    private javax.swing.JLabel tel;
    private javax.swing.JTextField tel1;
    private javax.swing.JComboBox<String> tipo_empleado;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
